const Features = () => {
  return (
    <section className="bg-[#EBE7DE] dark:bg-gray-800 transition-colors duration-300">
      {/* Feature Block 1 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 min-h-[80vh]">
        <div className="order-2 lg:order-1 relative h-[500px] lg:h-auto overflow-hidden">
           <img 
             src="https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&q=80&w=1200" 
             alt="Natural Stone Texture" 
             className="absolute inset-0 w-full h-full object-cover hover:scale-105 transition-transform duration-[1.5s]"
           />
        </div>
        <div className="order-1 lg:order-2 flex flex-col justify-center p-12 lg:p-24 bg-[#EBE7DE] dark:bg-gray-800 transition-colors duration-300">
           <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#A8A29E] dark:text-gray-500 mb-6 transition-colors duration-300">Our Philosophy</span>
           <h3 className="text-4xl md:text-5xl font-serif mb-8 text-[#2C2A26] dark:text-gray-100 leading-tight transition-colors duration-300">
             Content that <br/> resonates.
           </h3>
           <p className="text-lg text-[#5D5A53] dark:text-gray-300 font-light leading-relaxed mb-12 max-w-md transition-colors duration-300">
             We believe great content isn't just written—it's crafted. Every piece generated by CreatorAI is tailored to your voice, your audience, and your goals.
           </p>
           <a href="#about" className="inline-block text-sm font-medium uppercase tracking-widest underline underline-offset-8 hover:text-[#8C8881] dark:hover:text-gray-400 text-[#2C2A26] dark:text-gray-300 transition-colors">Learn more</a>
        </div>
      </div>

      {/* Feature Block 2 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 min-h-[80vh]">
        <div className="flex flex-col justify-center p-12 lg:p-24 bg-[#2C2A26] dark:bg-gray-900 text-[#F5F2EB] dark:text-gray-100 transition-colors duration-300">
           <span className="text-xs font-bold uppercase tracking-[0.2em] text-[#A8A29E] dark:text-gray-400 mb-6 transition-colors duration-300">The Experience</span>
           <h3 className="text-4xl md:text-5xl font-serif mb-8 text-[#F5F2EB] dark:text-gray-100 leading-tight transition-colors duration-300">
             Fast by default.
           </h3>
           <p className="text-lg text-[#A8A29E] dark:text-gray-300 font-light leading-relaxed mb-12 max-w-md transition-colors duration-300">
             Generate professional content in seconds. No waiting, no delays. Just pure creative power at your fingertips, whenever you need it.
           </p>
        </div>
        <div className="relative h-[500px] lg:h-auto overflow-hidden">
           <img 
             src="https://images.pexels.com/photos/6801917/pexels-photo-6801917.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" 
             alt="Creative workspace" 
             className="absolute inset-0 w-full h-full object-cover hover:scale-105 transition-transform duration-[1.5s] brightness-90"
           />
        </div>
      </div>
    </section>
  );
};

export default Features;

